server:
  port: 8090
spring:
  application:
    name: web
dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
  application:
    name: web #应用名
  consumer:
    timeout: 30000 #超时时间
service:
  version: 1.0.0 #自定义的版本，和消费者模块保持一致